fun main(){
    print ("  LABORATORIO DE ESTRUCTURA DE DATOS EN KOTLIN  ")
    reto1()
    reto2()
    reto3()
    reto4()
    reto5()
    reto6()
    reto7()
    reto8()
    reto9()
    reto10()
    reto11()
    reto12()
    print (" FIN DEL LABORATORIO ")
}